title: <p align="center"> Muhammad Abdul Aziz </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/muhammad-azizch/">LinkedIn</a> |
  <a href="https://github.com/muhammadazizch">GitHub</a>
  </p>
  
  <p align="justify">
  Bachelor Degree of Statisticsat Faculty of Science and Matematics, Diponegoro University.
  <br><br>
  I am currently a Mentee of Digistar Class Data Science | Data Analytics Study Independent  at Zenius |Ex-Internship as an Database Customer Supporting at PT Pegadaian
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
